import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aaghaaz 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#2864b8]'>
        {children}
      </body>
    </html>
  )
}
